# Generated by Django 4.2.4 on 2023-08-26 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_remove_review_movie_review_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='product',
            new_name='movie',
        ),
    ]
